---
sudo: required

# Based on :
# https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
# https://www.jeffgeerling.com/blog/2016/how-i-test-ansible-configuration-on-7-different-oses-docker
services: docker

env:
  - distro=centos7
  # - distro: centos6
  # - distro: ubuntu1604
  # - distro: ubuntu1404
  # - distro: ubuntu1204
  # - distro: debian8

script:
  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/lrk/6c86b9924e86b4152e882a25d320572f/raw/8b08620cbfa2f31da20436760e0e91d85557f488/ansible-role-test.sh
  - chmod +x ${PWD}/tests/test.sh
  # Run tests.
  - ${PWD}/tests/test.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
