---
# tasks file for ansible-role-kibana/
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: "Ensure Kibana is installed"
  package:
    name: kibana
    state: present

- name: "Check if kibana use initd"
  stat:
    path: /etc/init.d/kibana
  register: kibana_etc_initd

- name: "Check if kibana use systemd"
  stat:
    path: /etc/systemd/system/kibana.service
  register: kibana_systemd_service

- name: "Update Kibana initd service unit"
  lineinfile:
    dest: /etc/init.d/kibana
    line: '  touch $pidfile && chown $user:$group $pidfile'
    insertafter: '^\s*# Setup any environmental stuff beforehand$'
  become: yes
  when: kibana_etc_initd.stat.exists

- name: "Update Kibana systemd service unit"
  blockinfile:
    dest: /etc/systemd/system/kibana.service
    block: |
      PermissionsStartOnly=true
      ExecStartPre=/bin/touch {{ kibana_pid_file }}
      ExecStartPre=/bin/chown {{ __kibana_user }}:{{ __kibana_group }} {{ kibana_pid_file }}
    insertafter: '^\[Service\]'
  register: kibana_systemd_service
  become: yes
  when: kibana_systemd_service.stat.exists

- name: "Ensure systemd reloaded"
  systemd:
    daemon_reload: yes
  when: kibana_systemd_service.changed

- name: "Ensure Kibana is started and enabled at boot."
  service:
    name: kibana
    state: started
    enabled: yes

- name: "Ensure Kibana is configured."
  template:
    src: kibana.yml.j2
    dest: "/etc/kibana/kibana.yml"
    force: yes
    owner: "{{ __kibana_user }}"
    group: "{{ __kibana_group }}"
    mode: "u=rw,g=r,o="
  notify: "restart kibana"
