---
# tasks file for ansible-role-kibana/
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: "Ensure Kibana is installed"
  package:
    name: kibana
    state: present

- name: "Ensure Kibana PID exists"
  become: true
  file:
    path: "{{ kibana_pid_file }}"
    state: file
    owner: "{{ __kibana_user }}"
    group: "{{ __kibana_group }}"
    mode: "u=rw,g=r,o="

- name: "Ensure Kibana is started and enabled at boot."
  service:
    name: kibana
    state: started
    enabled: yes

- name: "Ensure Kibana is configured."
  template:
    src: kibana.yml.j2
    dest: "/etc/kibana/kibana.yml"
    owner: "{{ __kibana_user }}"
    group: "{{ __kibana_group }}"
    mode: "u=rw,g=r,o="
  notify: "restart kibana"
